/**
 * ============================================================================
 * SREE AMBAL CATERING — 200+ SOUTH INDIAN CATERING CATALOG (catalog.js)
 * Categories: Grains, Spices, Oils, Sweeteners, Perishables, Dairy, Nuts, Utensils
 * Languages supported: EN, TA (Tamil), ML (Malayalam), HI (Hindi), TE (Telugu)
 * ============================================================================
 */

const SOUTH_INDIAN_CATALOG = [
  // 1. GRAINS & PULSES (தானியங்கள் & பருப்புகள்) — ~30 items
  { id: 'item-g-01', category: 'grains', defaultUnit: 'kg', names: { en: 'Ponni Boiled Rice', ta: 'பொன்னி புழுங்கல் அரிசி', ml: 'പൊന്നി പുഴുങ്ങലരി', hi: 'पोन्नी उबला चावल', te: 'పొన్ని ఉడికించిన బియ్యం' } },
  { id: 'item-g-02', category: 'grains', defaultUnit: 'kg', names: { en: 'Ponni Raw Rice', ta: 'பொன்னி பச்சரிசி', ml: 'പൊന്നി പച്ചരി', hi: 'पोन्नी कच्चा चावल', te: 'పొన్ని పచ్చి బియ్యం' } },
  { id: 'item-g-03', category: 'grains', defaultUnit: 'kg', names: { en: 'Basmati Rice (Long Grain)', ta: 'பாசுமதி அரிசி', ml: 'ബസുമതി അരി', hi: 'बासमती चावल', te: 'బాస్మతి బియ్యం' } },
  { id: 'item-g-04', category: 'grains', defaultUnit: 'kg', names: { en: 'Seeraga Samba Rice (Biryani)', ta: 'சீரகச் சம்பா அரிசி', ml: 'ജീരകശാല അരി', hi: 'जीरा सांबा चावल', te: 'జీరగ సాంబ బియ్యం' } },
  { id: 'item-g-05', category: 'grains', defaultUnit: 'kg', names: { en: 'Idli Rice (Parboiled)', ta: 'இட்லி அரிசி', ml: 'ഇഡ്ഡലി അരി', hi: 'इड़ली चावल', te: 'ఇడ్లీ బియ్యం' } },
  { id: 'item-g-06', category: 'grains', defaultUnit: 'kg', names: { en: 'Sona Masoori Rice', ta: 'சோனா மசூரி அரிசி', ml: 'സോന മസൂരി അരി', hi: 'सोना मसूरी चावल', te: 'సోనా మసూరి బియ్యం' } },
  { id: 'item-g-07', category: 'grains', defaultUnit: 'kg', names: { en: 'Toor Dal (Pigeon Pea)', ta: 'துவரம் பருப்பு', ml: 'തുവര പരിപ്പ്', hi: 'अरहर दाल', te: 'కంది పప్పు' } },
  { id: 'item-g-08', category: 'grains', defaultUnit: 'kg', names: { en: 'Urad Dal Whole (White)', ta: 'உளுந்தம் பருப்பு (வெள்ளை)', ml: 'ഉഴുന്ന് പരിപ്പ്', hi: 'उड़द दाल सफेद', te: 'మినప పప్పు' } },
  { id: 'item-g-09', category: 'grains', defaultUnit: 'kg', names: { en: 'Urad Dal Split (Black)', ta: 'கருப்பு உளுந்து', ml: 'കറുത്ത ഉഴുന്ന്', hi: 'काली उड़द दाल', te: 'నల్ల మినపప్పు' } },
  { id: 'item-g-10', category: 'grains', defaultUnit: 'kg', names: { en: 'Moong Dal Split (Yellow)', ta: 'பாசிப் பருப்பு', ml: 'ചെറുപയർ പരിപ്പ്', hi: 'मूंग दाल', te: 'పెసర పప్పు' } },
  { id: 'item-g-11', category: 'grains', defaultUnit: 'kg', names: { en: 'Green Gram Whole (Moong)', ta: 'பச்சை பயறு', ml: 'ചെറുപയർ', hi: 'साबुत मूंग', te: 'పెసలు' } },
  { id: 'item-g-12', category: 'grains', defaultUnit: 'kg', names: { en: 'Chana Dal (Bengal Gram)', ta: 'கடலைப் பருப்பு', ml: 'കടല പരിപ്പ്', hi: 'चना दाल', te: 'శనగ పప్పు' } },
  { id: 'item-g-13', category: 'grains', defaultUnit: 'kg', names: { en: 'Black Chana (Brown Chickpeas)', ta: 'கருப்பு கொண்டைக்கடலை', ml: 'കറുത്ത കടല', hi: 'काला चना', te: 'నల్ల శనగలు' } },
  { id: 'item-g-14', category: 'grains', defaultUnit: 'kg', names: { en: 'White Chana (Kabuli Chana)', ta: 'வெள்ளை கொண்டைக்கடலை', ml: 'വെള്ള കടല', hi: 'काबुली चना', te: 'తెల్ల శనగలు' } },
  { id: 'item-g-15', category: 'grains', defaultUnit: 'kg', names: { en: 'Fried Gram (Pottukadalai)', ta: 'பொட்டுக்கடலை', ml: 'പൊട്ടുകടല', hi: 'भुना चना', te: 'పుట్నాల పప్పు' } },
  { id: 'item-g-16', category: 'grains', defaultUnit: 'kg', names: { en: 'Masoor Dal (Red Lentil)', ta: 'மசூர் பருப்பு', ml: 'മസൂർ പരിപ്പ്', hi: 'मसूर दाल', te: 'మసూర్ పప్పు' } },
  { id: 'item-g-17', category: 'grains', defaultUnit: 'kg', names: { en: 'Horse Gram (Kollu)', ta: 'கொள்ளு', ml: 'മുതിര', hi: 'कुलथी दाल', te: 'ఉలవలు' } },
  { id: 'item-g-18', category: 'grains', defaultUnit: 'kg', names: { en: 'Rajma (Red Kidney Beans)', ta: 'ராஜ்மா', ml: 'രാജ്മ', hi: 'राजमा', te: 'రాజ్మా' } },
  { id: 'item-g-19', category: 'grains', defaultUnit: 'kg', names: { en: 'Black Eyed Peas (Karamani)', ta: 'காராமணி', ml: 'വൻപയർ', hi: 'लोबिया', te: 'అలసందలు' } },
  { id: 'item-g-20', category: 'grains', defaultUnit: 'kg', names: { en: 'Wheat Flour (Atta)', ta: 'கோதுமை மாவு', ml: 'ഗോതമ്പ് പൊടി', hi: 'गेहूं का आटा', te: 'గోధుమ పిండి' } },
  { id: 'item-g-21', category: 'grains', defaultUnit: 'kg', names: { en: 'Maida (Refined Flour)', ta: 'மைதா மாவு', ml: 'മൈദ', hi: 'मैदा', te: 'మైదా పిండి' } },
  { id: 'item-g-22', category: 'grains', defaultUnit: 'kg', names: { en: 'Besan (Gram Flour)', ta: 'கடலை மாவு', ml: 'കടലമാവ്', hi: 'बेसन', te: 'శనగ పిండి' } },
  { id: 'item-g-23', category: 'grains', defaultUnit: 'kg', names: { en: 'Rice Flour (Pacharisi Mavu)', ta: 'அரிசி மாவு', ml: 'അരിപ്പൊടി', hi: 'चावल का आटा', te: 'బియ్యం పిండి' } },
  { id: 'item-g-24', category: 'grains', defaultUnit: 'kg', names: { en: 'Ragi Flour (Finger Millet)', ta: 'கேழ்வரகு மாவு', ml: 'രാഗി പൊടി', hi: 'रागी का आटा', te: 'రాగి పిండి' } },
  { id: 'item-g-25', category: 'grains', defaultUnit: 'kg', names: { en: 'Sooji / Rava (Semolina)', ta: 'ரவை', ml: 'റവ', hi: 'सूजी / रवा', te: 'బొంబాయి రవ్వ' } },
  { id: 'item-g-26', category: 'grains', defaultUnit: 'kg', names: { en: 'Wheat Rava (Broken Wheat)', ta: 'கோதுமை ரவை', ml: 'ഗോതമ്പ് റവ', hi: 'दलिया', te: 'గోధుమ రవ్వ' } },
  { id: 'item-g-27', category: 'grains', defaultUnit: 'kg', names: { en: 'Semiya (Vermicelli - Roasted)', ta: 'சேமியா', ml: 'സേമിയ', hi: 'सेवई', te: 'సేమియా' } },
  { id: 'item-g-28', category: 'grains', defaultUnit: 'kg', names: { en: 'Poha / Aval (Flattened Rice)', ta: 'அவல்', ml: 'അവൽ', hi: 'पोहा', te: 'అటుకులు' } },
  { id: 'item-g-29', category: 'grains', defaultUnit: 'kg', names: { en: 'Sabudana (Javvarisi / Sago)', ta: 'ஜவ்வரிசி', ml: 'ചൗവരി', hi: 'साबूदाना', te: 'సగ్గుబియ్యం' } },
  { id: 'item-g-30', category: 'grains', defaultUnit: 'kg', names: { en: 'Corn Flour / Starch', ta: 'சோள மாவு', ml: 'കോൺഫ്ലോർ', hi: 'कॉर्न फ्लोर', te: 'మొక్కజొన్న పిండి' } },

  // 2. SPICES & MASALAS (மசாலா & வாசனை திரவியங்கள்) — ~35 items
  { id: 'item-s-01', category: 'spices', defaultUnit: 'kg', names: { en: 'Turmeric Powder (Manjal)', ta: 'மஞ்சள் தூள்', ml: 'മഞ്ഞൾ പൊടി', hi: 'हल्दी पाउडर', te: 'పసుపు పొడి' } },
  { id: 'item-s-02', category: 'spices', defaultUnit: 'kg', names: { en: 'Red Chilli Powder (Milagai)', ta: 'மிளகாய் தூள்', ml: 'മുളക് പൊടി', hi: 'लाल मिर्च पाउडर', te: 'కారపు పొడి' } },
  { id: 'item-s-03', category: 'spices', defaultUnit: 'kg', names: { en: 'Kashmiri Chilli Powder', ta: 'காஷ்மீரி மிளகாய் தூள்', ml: 'കാശ്മീരി മുളക് പൊടി', hi: 'कश्मीरी मिर्च पाउडर', te: 'కాశ్మీరీ మిర్చి పొడి' } },
  { id: 'item-s-04', category: 'spices', defaultUnit: 'kg', names: { en: 'Coriander Powder (Malli)', ta: 'கொத்தமல்லி தூள்', ml: 'മല്ലിപ്പൊടി', hi: 'धनिया पाउडर', te: 'ధనియాల పొడి' } },
  { id: 'item-s-05', category: 'spices', defaultUnit: 'kg', names: { en: 'Sambar Powder (Special)', ta: 'சாம்பார் பொடி', ml: 'സാമ്പാർ പൊടി', hi: 'सांभर मसाला', te: 'సాంబార్ పొడి' } },
  { id: 'item-s-06', category: 'spices', defaultUnit: 'kg', names: { en: 'Rasam Powder', ta: 'ரசம் பொடி', ml: 'രസം പൊടി', hi: 'रसम मसाला', te: 'రసం పొడి' } },
  { id: 'item-s-07', category: 'spices', defaultUnit: 'kg', names: { en: 'Idli Milagai Podi (Gunpowder)', ta: 'இட்லி மிளகாய் பொடி', ml: 'ഇഡ്ഡലി പൊടി', hi: 'इड़ली पोडी मसाला', te: 'ఇడ్లీ కారం పొడి' } },
  { id: 'item-s-08', category: 'spices', defaultUnit: 'kg', names: { en: 'Garam Masala Powder', ta: 'கரம் மசாலா', ml: 'ഗരം മസാല', hi: 'गरम मसाला', te: 'గరం మసాలా' } },
  { id: 'item-s-09', category: 'spices', defaultUnit: 'kg', names: { en: 'Biryani Masala Powder', ta: 'பிரியாணி மசாலா', ml: 'ബിരിയാണി മസാല', hi: 'बिरयानी मसाला', te: 'బిర్యానీ మసాలా' } },
  { id: 'item-s-10', category: 'spices', defaultUnit: 'kg', names: { en: 'Black Pepper Whole (Milagu)', ta: 'மிளகு', ml: 'കുരുമുളക്', hi: 'काली मिर्च', te: 'మిరియాలు' } },
  { id: 'item-s-11', category: 'spices', defaultUnit: 'kg', names: { en: 'Black Pepper Powder', ta: 'மிளகு தூள்', ml: 'കുരുമുളക് പൊടി', hi: 'काली मिर्च पाउडर', te: 'మిరియాల పొడి' } },
  { id: 'item-s-12', category: 'spices', defaultUnit: 'kg', names: { en: 'Cumin Seeds (Seeragam)', ta: 'சீரகம்', ml: 'ജീരകം', hi: 'जीरा', te: 'జీలకర్ర' } },
  { id: 'item-s-13', category: 'spices', defaultUnit: 'kg', names: { en: 'Cumin Powder', ta: 'சீரகத் தூள்', ml: 'ജീരകപ്പൊടി', hi: 'जीरा पाउडर', te: 'జీలకర్ర పొడి' } },
  { id: 'item-s-14', category: 'spices', defaultUnit: 'kg', names: { en: 'Mustard Seeds (Kadugu)', ta: 'கடுகு', ml: 'കടുക്', hi: 'सरसों / राई', te: 'ఆవాలు' } },
  { id: 'item-s-15', category: 'spices', defaultUnit: 'kg', names: { en: 'Fenugreek Seeds (Vendhayam)', ta: 'வெந்தயம்', ml: 'ഉലുവ', hi: 'मेथी दाना', te: 'మెంతులు' } },
  { id: 'item-s-16', category: 'spices', defaultUnit: 'kg', names: { en: 'Fennel Seeds (Sombu)', ta: 'சோம்பு / பெருஞ்சீரகம்', ml: 'പെരുംജീരകം', hi: 'सौंफ', te: 'సోంపు' } },
  { id: 'item-s-17', category: 'spices', defaultUnit: 'kg', names: { en: 'Coriander Seeds Whole', ta: 'வர கொத்தமல்லி', ml: 'മല്ലി', hi: 'साबुत धनिया', te: 'ధనియాలు' } },
  { id: 'item-s-18', category: 'spices', defaultUnit: 'kg', names: { en: 'Dry Red Chillies (Guntur/Sanaram)', ta: 'வர மிளகாய்', ml: 'വറ്റൽ മുളക്', hi: 'सूखी लाल मिर्च', te: 'ఎండు మిర్చి' } },
  { id: 'item-s-19', category: 'spices', defaultUnit: 'kg', names: { en: 'Green Cardamom (Elakai)', ta: 'ஏலக்காய்', ml: 'ഏലക്ക', hi: 'हरी इलायची', te: 'యాలకులు' } },
  { id: 'item-s-20', category: 'spices', defaultUnit: 'kg', names: { en: 'Cloves (Kirambu)', ta: 'கிராம்பு / லவங்கம்', ml: 'ഗ്രാമ്പൂ', hi: 'लौंग', te: 'లవంగాలు' } },
  { id: 'item-s-21', category: 'spices', defaultUnit: 'kg', names: { en: 'Cinnamon Sticks (Pattai)', ta: 'பட்டை', ml: 'കറുവപ്പട്ട', hi: 'दालचीनी', te: 'దాల్చిన చెక్క' } },
  { id: 'item-s-22', category: 'spices', defaultUnit: 'kg', names: { en: 'Star Anise (Anaipu Pu)', ta: 'அன்னாசி பூ', ml: 'തക്കോലം', hi: 'चक्र फूल', te: 'అనాస పువ్వు' } },
  { id: 'item-s-23', category: 'spices', defaultUnit: 'kg', names: { en: 'Bay Leaves (Biryani Leaf)', ta: 'பிரியாணி இலை', ml: 'കറുവപ്പട്ട ഇല', hi: 'तेज पत्ता', te: 'బిర్యానీ ఆకు' } },
  { id: 'item-s-24', category: 'spices', defaultUnit: 'kg', names: { en: 'Nutmeg (Jathikai)', ta: 'ஜாதிக்காய்', ml: 'ജാതിക്ക', hi: 'जायफल', te: 'జాజికాయ' } },
  { id: 'item-s-25', category: 'spices', defaultUnit: 'kg', names: { en: 'Mace (Jathipatri)', ta: 'ஜாதிப்பத்திரி', ml: 'ജാതിപത്രി', hi: 'जावित्री', te: 'జాపత్రి' } },
  { id: 'item-s-26', category: 'spices', defaultUnit: 'kg', names: { en: 'Kalpasi (Black Stone Flower)', ta: 'கல்பாசி', ml: 'കൽപ്പാശി', hi: 'पत्थर के फूल', te: 'కల్పాసి / బండ పువ్వు' } },
  { id: 'item-s-27', category: 'spices', defaultUnit: 'kg', names: { en: 'Kapok Buds (Marathi Moggu)', ta: 'மராட்டி மொக்கு', ml: 'മറാഠി മൊഗ്ഗു', hi: 'मराठी मोग्गु', te: 'మరాఠీ మొగ్గ' } },
  { id: 'item-s-28', category: 'spices', defaultUnit: 'kg', names: { en: 'Asafoetida Powder (Perungayam)', ta: 'பெருங்காயத் தூள்', ml: 'കായം', hi: 'हींग', te: 'ఇంగువ' } },
  { id: 'item-s-29', category: 'spices', defaultUnit: 'kg', names: { en: 'Asafoetida Cake (Katti Perungayam)', ta: 'கட்டி பெருங்காயம்', ml: 'കട്ടി കായം', hi: 'हींग का टुकड़ा', te: 'కట్టి ఇంగువ' } },
  { id: 'item-s-30', category: 'spices', defaultUnit: 'kg', names: { en: 'Kasuri Methi (Dry Fenugreek Leaf)', ta: 'கஸ்தூரி மேத்தி', ml: 'കസ്തൂരി മേത്തി', hi: 'कसूरी मेथी', te: 'కస్తూరి మేతి' } },
  { id: 'item-s-31', category: 'spices', defaultUnit: 'kg', names: { en: 'Poppy Seeds (Kasa Kasa)', ta: 'கசகசா', ml: 'കശകശ', hi: 'खसखस', te: 'గసగసాలు' } },
  { id: 'item-s-32', category: 'spices', defaultUnit: 'kg', names: { en: 'White Pepper Powder', ta: 'வெள்ளை மிளகு தூள்', ml: 'വെള്ള കുരുമുളക് പൊടി', hi: 'सफेद मिर्च', te: 'తెల్ల మిరియాల పొడి' } },
  { id: 'item-s-33', category: 'spices', defaultUnit: 'kg', names: { en: 'Dry Ginger Powder (Chukku)', ta: 'சுக்கு பொடி', ml: 'ചുക്കു പൊടി', hi: 'सोंठ पाउडर', te: 'సొంటి పొడి' } },
  { id: 'item-s-34', category: 'spices', defaultUnit: 'kg', names: { en: 'Rock Salt (Indhu Uppu)', ta: 'இந்துப்பு', ml: 'ഇന്തുപ്പ്', hi: 'सेंधा नमक', te: 'సైంధవ లవణం' } },
  { id: 'item-s-35', category: 'spices', defaultUnit: 'kg', names: { en: 'Iodized Crystal Salt (Kalluppu)', ta: 'கல் உப்பு', ml: 'കല്ലുപ്പ്', hi: 'खड़ा नमक', te: 'కల్లు ఉప్పు' } },

  // 3. OILS & GHEE (எண்ணெய்கள் & நெய்) — ~15 items
  { id: 'item-o-01', category: 'oils', defaultUnit: 'L', names: { en: 'Agmark Pure Cow Ghee', ta: 'அக்மார்க் சுத்தமான பசு நெய்', ml: 'പശു നെയ്യ്', hi: 'शुद्ध गाय का घी', te: 'ఆవు నెయ్యి' } },
  { id: 'item-o-02', category: 'oils', defaultUnit: 'L', names: { en: 'Buffalo Ghee (Commercial)', ta: 'எருமை நெய்', ml: 'എരുമ നെയ്യ്', hi: 'भैंस का घी', te: 'గెదె నెయ్యి' } },
  { id: 'item-o-03', category: 'oils', defaultUnit: 'L', names: { en: 'Gingelly Oil (Cold Pressed Nallennai)', ta: 'செக்கு நல்லெண்ணெய்', ml: 'നല്ലെണ്ണ', hi: 'तिल का तेल', te: 'నువ్వుల నూనె' } },
  { id: 'item-o-04', category: 'oils', defaultUnit: 'L', names: { en: 'Coconut Oil (Pure Roasted)', ta: 'சுத்தமான தேங்காய் எண்ணெய்', ml: 'വെളിച്ചെണ്ണ', hi: 'नारियल का तेल', te: 'కొబ్బరి నూనె' } },
  { id: 'item-o-05', category: 'oils', defaultUnit: 'L', names: { en: 'Refined Sunflower Oil', ta: 'சூரியகாந்தி எண்ணெய்', ml: 'സൂര്യകാന്തി എണ്ണ', hi: 'सूरजमुखी का तेल', te: 'సొద్దుతిరుగుడు నూనె' } },
  { id: 'item-o-06', category: 'oils', defaultUnit: 'L', names: { en: 'Groundnut / Peanut Oil (Kadalai Ennai)', ta: 'கடலை எண்ணெய்', ml: 'കടല എണ്ണ', hi: 'मूंगफली का तेल', te: 'వేరుశనగ నూనె' } },
  { id: 'item-o-07', category: 'oils', defaultUnit: 'L', names: { en: 'Palmolein Oil (Frying Grade)', ta: 'பாமாயில்', ml: 'പാമോയിൽ', hi: 'पाम ऑयल', te: 'పామాయిల్' } },
  { id: 'item-o-08', category: 'oils', defaultUnit: 'L', names: { en: 'Mustard Oil (Kadu Ennai)', ta: 'கடுகு எண்ணெய்', ml: 'കടുക് എണ്ണ', hi: 'सरसों का तेल', te: 'ఆవ నూనె' } },
  { id: 'item-o-09', category: 'oils', defaultUnit: 'L', names: { en: 'Castor Oil (Vilakkennai)', ta: 'விளக்கெண்ணெய்', ml: 'ആവണക്കെണ്ണ', hi: 'अरंडी का तेल', te: 'ఆముదం నూనె' } },
  { id: 'item-o-10', category: 'oils', defaultUnit: 'L', names: { en: 'Rice Bran Oil', ta: 'தவிடு எண்ணெய்', ml: 'റൈസ് ബ്രാൻ എണ്ണ', hi: 'राइस ब्रान ऑयल', te: 'తవుడు నూనె' } },
  { id: 'item-o-11', category: 'oils', defaultUnit: 'kg', names: { en: 'Vanaspati / Dalda (Hydrogenated Fat)', ta: 'வனஸ்பதி / டால்டா', ml: 'വനസ്പതി', hi: 'वनस्पति घी / डालडा', te: 'డాల్డా / వనస్పతి' } },
  { id: 'item-o-12', category: 'oils', defaultUnit: 'tins', names: { en: '15L Oil Tin — Sunflower', ta: '15 லிட்டர் டின் — சூரியகாந்தி', ml: '15L എണ്ണ ടിൻ — സൂര്യകാന്തി', hi: '15L तेल का टीन — सूरजमुखी', te: '15L నూనె డబ్బా — సన్ ఫ్లవర్' } },
  { id: 'item-o-13', category: 'oils', defaultUnit: 'tins', names: { en: '15L Oil Tin — Palmolein', ta: '15 லிட்டர் டின் — பாமாயில்', ml: '15L എണ്ണ ടിൻ — പാമോയിൽ', hi: '15L तेल का टीन — पाम ऑयल', te: '15L నూనె డబ్బా — పామాయిల్' } },
  { id: 'item-o-14', category: 'oils', defaultUnit: 'tins', names: { en: '15kg Ghee Tin — Agmark', ta: '15 கிலோ நெய் டின்', ml: '15L നെയ്യ് ടിൻ', hi: '15kg घी का टीन', te: '15kg నెయ్యి డబ్బా' } },
  { id: 'item-o-15', category: 'oils', defaultUnit: 'L', names: { en: 'Deep Frying Blended Oil', ta: 'பொரிப்பு எண்ணெய்', ml: 'വറുക്കാനുള്ള എണ്ണ', hi: 'तलने का तेल', te: 'వేపుడు నూనె' } },

  // 4. SWEETENERS & ACIDULANTS (இனிப்புகள் & புளிப்பு) — ~15 items
  { id: 'item-sw-01', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Refined White Sugar (Sakkarei)', ta: 'சர்க்கரை / ஜீனி', ml: 'പഞ്ചസാര', hi: 'चीनी', te: 'చక్కెర' } },
  { id: 'item-sw-02', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Round Jaggery Balls (Vellam)', ta: 'உருண்டை வெல்லம்', ml: 'ശർക്കര', hi: 'गुड़', te: 'బెల్లం' } },
  { id: 'item-sw-03', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Organic Brown Jaggery Powder', ta: 'நாட்டுச் சர்க்கரை', ml: 'കരിപ്പെട്ടി പൊടി', hi: 'शक्कर गुड़ पाउडर', te: 'సేంద్రియ బెల్లం పొడి' } },
  { id: 'item-sw-04', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Palm Jaggery (Karupatti)', ta: 'கருப்பட்டி', ml: 'കരിപ്പെട്ടി', hi: 'ताड़ का गुड़', te: 'తాటి బెల్లం' } },
  { id: 'item-sw-05', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Palm Sugar Candy (Panakarkandu)', ta: 'பனங்கற்கண்டு', ml: 'പനംകൽക്കണ്ടം', hi: 'ताड़ मिश्री', te: 'తాటి కలకండ' } },
  { id: 'item-sw-06', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'White Diamond Mishri (Kalkandu)', ta: 'கற்கண்டு', ml: 'കൽക്കണ്ടം', hi: 'मिश्री', te: 'పటిక బెల్లం' } },
  { id: 'item-sw-07', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Tamarind Paste (Aged Puli)', ta: 'பழைய புளி', ml: 'പുളി', hi: 'इमली', te: 'చింతపండు' } },
  { id: 'item-sw-08', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Seedless Tamarind Slab', ta: 'கொட்டை நீக்கிய புளி', ml: 'കുരുവില്ലാത്ത പുളി', hi: 'बिना बीज की इमली', te: 'గింజలు లేని చింతపండు' } },
  { id: 'item-sw-09', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Kokum Petals (Kudampuli)', ta: 'குடம்புளி', ml: 'കുടംപുളി', hi: 'कोकम', te: 'కోకమ్' } },
  { id: 'item-sw-10', category: 'sweeteners', defaultUnit: 'L', names: { en: 'Synthetic White Vinegar', ta: 'வெள்ளை வினிகர்', ml: 'വിനാഗിരി', hi: 'सफेद सिरका', te: 'తెల్ల వెనిగర్' } },
  { id: 'item-sw-11', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Citric Acid Crystals (Lemon Salt)', ta: 'எலுமிச்சை உப்பு', ml: 'സിട്രിക് ആസിഡ്', hi: 'नींबू सत', te: 'నిమ్మ ఉప్పు' } },
  { id: 'item-sw-12', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Dry Mango Powder (Amchur)', ta: 'மாங்காய் தூள்', ml: 'മാങ്ങ പൊടി', hi: 'आमचूर पाउडर', te: 'మామిడికాయ పొడి' } },
  { id: 'item-sw-13', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Liquid Glucose (Sweets Binder)', ta: 'திரவ குளுக்கோஸ்', ml: 'ലിക്വിഡ് ഗ്ലൂക്കോസ്', hi: 'लिक्विड ग्लूकोज', te: 'ద్రవ గ్లూకోజ్' } },
  { id: 'item-sw-14', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Food Grade Baking Soda', ta: 'ஆப்ப சோடா / சமையல் சோடா', ml: 'അപ്പക്കാരം', hi: 'बेकिंग सोडा', te: 'వంట సోడా' } },
  { id: 'item-sw-15', category: 'sweeteners', defaultUnit: 'kg', names: { en: 'Yeast (Dry Active for Appam)', ta: 'ஈஸ்ட்', ml: 'ഈസ്റ്റ്', hi: 'खमीर', te: 'ఈస్ట్' } },

  // 5. VEGETABLES & PERISHABLES (காய்கறிகள் & கீரைகள்) — ~35 items
  { id: 'item-p-01', category: 'perishables', defaultUnit: 'kg', names: { en: 'Red Onions (Big Pallari)', ta: 'பெரிய வெங்காயம் / பல்லாரி', ml: 'സവാള', hi: 'प्याज बड़ा', te: 'ఉల్లిపాయలు' } },
  { id: 'item-p-02', category: 'perishables', defaultUnit: 'kg', names: { en: 'Small Shallots (Sambar Onion)', ta: 'சின்ன வெங்காயம்', ml: 'ചെറിയ ഉള്ളി', hi: 'छोटा प्याज', te: 'చిన్న ఉల్లిపాయలు' } },
  { id: 'item-p-03', category: 'perishables', defaultUnit: 'kg', names: { en: 'Country Tomatoes (Nattu Thakkali)', ta: 'நாட்டுத் தக்காளி', ml: 'നാടൻ തക്കാളി', hi: 'देसी टमाटर', te: 'నాటు టమోటాలు' } },
  { id: 'item-p-04', category: 'perishables', defaultUnit: 'kg', names: { en: 'Hybrid Salad Tomatoes', ta: 'ஆப்பிள் தக்காளி', ml: 'ഹൈബ്രിഡ് തക്കാളി', hi: 'सलाद टमाटर', te: 'హైబ్రిడ్ టమోటాలు' } },
  { id: 'item-p-05', category: 'perishables', defaultUnit: 'kg', names: { en: 'Fresh Green Chillies', ta: 'பச்சை மிளகாய்', ml: 'പച്ചമുളക്', hi: 'हरी मिर्च', te: 'పచ్చి మిర్చి' } },
  { id: 'item-p-06', category: 'perishables', defaultUnit: 'kg', names: { en: 'Fresh Ginger Root (Inji)', ta: 'இஞ்சி', ml: 'ഇഞ്ചി', hi: 'अदरक', te: 'అల్లం' } },
  { id: 'item-p-07', category: 'perishables', defaultUnit: 'kg', names: { en: 'Fresh Garlic Bulbs (Poondu)', ta: 'பூண்டு', ml: 'വെളുത്തുള്ളി', hi: 'लहसुन', te: 'వెల్లుల్లి' } },
  { id: 'item-p-08', category: 'perishables', defaultUnit: 'kg', names: { en: 'Curry Leaves (Karuveppilai)', ta: 'கறிவேப்பிலை', ml: 'കറിവേപ്പില', hi: 'कड़ी पत्ता', te: 'కరివేపాకు' } },
  { id: 'item-p-09', category: 'perishables', defaultUnit: 'kg', names: { en: 'Coriander Leaves (Kothamalli)', ta: 'கொத்தமல்லி தழை', ml: 'മല്ലയില', hi: 'हरा धनिया', te: 'కొత్తిమీర' } },
  { id: 'item-p-10', category: 'perishables', defaultUnit: 'kg', names: { en: 'Mint Leaves (Pudina)', ta: 'புதினா', ml: 'പുതിന', hi: 'पुदीना', te: 'పుదీనా' } },
  { id: 'item-p-11', category: 'perishables', defaultUnit: 'pcs', names: { en: 'Fresh Mature Coconuts', ta: 'தேங்காய் (முற்றியது)', ml: 'തേങ്ങ', hi: 'नारियल साबुत', te: 'కొబ్బరికాయలు' } },
  { id: 'item-p-12', category: 'perishables', defaultUnit: 'kg', names: { en: 'Grated Frozen Coconut', ta: 'துருவிய தேங்காய்', ml: 'ചിരകിയ തേങ്ങ', hi: 'घिसा नारियल', te: 'తురిమిన కొబ్బరి' } },
  { id: 'item-p-13', category: 'perishables', defaultUnit: 'kg', names: { en: 'Drumsticks (Murungakkai)', ta: 'முருங்கைக்காய்', ml: 'മുരിങ്ങക്കായ', hi: 'सहजन / मोरिंगा', te: 'ములక్కాడలు' } },
  { id: 'item-p-14', category: 'perishables', defaultUnit: 'kg', names: { en: 'Brinjal / Eggplant (Kathirikkai)', ta: 'கத்தரிக்காய்', ml: 'വഴുതനങ്ങ', hi: 'बैंगन', te: 'వంకాయ' } },
  { id: 'item-p-15', category: 'perishables', defaultUnit: 'kg', names: { en: 'Ladies Finger (Okra / Vendakkai)', ta: 'வெண்டைக்காய்', ml: 'വെണ്ടയ്ക്ക', hi: 'भिंडी', te: 'బెండకాయ' } },
  { id: 'item-p-16', category: 'perishables', defaultUnit: 'kg', names: { en: 'Bottle Gourd (Suraikkai)', ta: 'சுரைக்காய்', ml: 'ചുരയ്ക്ക', hi: 'लौकी', te: 'సొరకాయ' } },
  { id: 'item-p-17', category: 'perishables', defaultUnit: 'kg', names: { en: 'Ash Gourd (Poosanikkai)', ta: 'வெள்ளை பூசணிக்காய்', ml: 'കുമ്പളങ്ങ', hi: 'पेठा / सफेद कद्दू', te: 'బూడిద గుమ్మడికాయ' } },
  { id: 'item-p-18', category: 'perishables', defaultUnit: 'kg', names: { en: 'Yellow Pumpkin (Parangikkai)', ta: 'மஞ்சள் பூசணிக்காய்', ml: 'മത്തങ്ങ', hi: 'पीला कद्दू', te: 'తియ్య గుమ్మడికాయ' } },
  { id: 'item-p-19', category: 'perishables', defaultUnit: 'kg', names: { en: 'Snake Gourd (Pudalangai)', ta: 'புடலங்காய்', ml: 'പടവലങ്ങ', hi: 'चिचिंडा', te: 'పొట్లకాయ' } },
  { id: 'item-p-20', category: 'perishables', defaultUnit: 'kg', names: { en: 'Bitter Gourd (Pavakkai)', ta: 'பாகற்காய்', ml: 'പാവയ്ക്ക', hi: 'करेला', te: 'కాకరకాయ' } },
  { id: 'item-p-21', category: 'perishables', defaultUnit: 'kg', names: { en: 'Ridge Gourd (Peerkangai)', ta: 'பீர்கங்காய்', ml: 'പീച്ചിങ്ങ', hi: 'तोरई', te: 'బీరకాయ' } },
  { id: 'item-p-22', category: 'perishables', defaultUnit: 'kg', names: { en: 'Broad Beans (Avarakkai)', ta: 'அவரைக்காய்', ml: 'അമരയ്ക്ക', hi: 'सेम की फली', te: 'చిక్కుడుకాయ' } },
  { id: 'item-p-23', category: 'perishables', defaultUnit: 'kg', names: { en: 'Cluster Beans (Kothavarangai)', ta: 'கொத்தவரங்காய்', ml: 'കൊത്തവരയ്ക്ക', hi: 'गंवार फली', te: 'గోరుచిక్కుడు' } },
  { id: 'item-p-24', category: 'perishables', defaultUnit: 'kg', names: { en: 'Raw Green Bananas (Valakkai)', ta: 'வாழைக்காய்', ml: 'വാഴയ്ക്ക', hi: 'कच्चा केला', te: 'అరటికాయ' } },
  { id: 'item-p-25', category: 'perishables', defaultUnit: 'kg', names: { en: 'Elephant Foot Yam (Senai Kizhangu)', ta: 'சேனைக்கிழங்கு', ml: 'ചേന', hi: 'जिमीकंद / सूरन', te: 'కంద గడ్డ' } },
  { id: 'item-p-26', category: 'perishables', defaultUnit: 'kg', names: { en: 'Colocasia / Taro Root (Seppankizhangu)', ta: 'சேப்பங்கிழங்கு', ml: 'ചേമ്പ്', hi: 'अरबी', te: 'చామగడ్డ' } },
  { id: 'item-p-27', category: 'perishables', defaultUnit: 'kg', names: { en: 'Potatoes (Urulaikizhangu)', ta: 'உருளைக்கிழங்கு', ml: 'ഉരുളക്കിഴങ്ങ്', hi: 'आलू', te: 'బంగాళాదుంపలు' } },
  { id: 'item-p-28', category: 'perishables', defaultUnit: 'kg', names: { en: 'Carrots (Red & Orange)', ta: 'காரட்', ml: 'കാരറ്റ്', hi: 'गाजर', te: 'క్యారెట్' } },
  { id: 'item-p-29', category: 'perishables', defaultUnit: 'kg', names: { en: 'Green Beans (French Beans)', ta: 'பீன்ஸ்', ml: 'ബീൻസ്', hi: 'हरी बीन्स', te: 'బీన్స్' } },
  { id: 'item-p-30', category: 'perishables', defaultUnit: 'kg', names: { en: 'Cabbage (Muttaikose)', ta: 'முட்டைக்கோஸ்', ml: 'ക്യാബേജ്', hi: 'पत्ता गोभी', te: 'క్యాబేజీ' } },
  { id: 'item-p-31', category: 'perishables', defaultUnit: 'kg', names: { en: 'Cauliflower Florets', ta: 'காலிபிளவர்', ml: 'കോളിഫ്ലവർ', hi: 'फूल गोभी', te: 'కాలీఫ్లవర్' } },
  { id: 'item-p-32', category: 'perishables', defaultUnit: 'kg', names: { en: 'Green Peas (Fresh/Frozen Tattapayaru)', ta: 'பச்சை பட்டாணி', ml: 'ഗ്രീൻ പീസ്', hi: 'हरी मटर', te: 'పచ్చి బఠాణీలు' } },
  { id: 'item-p-33', category: 'perishables', defaultUnit: 'kg', names: { en: 'Fresh Raw Mango (Sour for Sambar)', ta: 'பச்சை மாங்காய்', ml: 'പച്ച മാങ്ങ', hi: 'कच्चा आम', te: 'పచ్చి మామిడికాయ' } },
  { id: 'item-p-34', category: 'perishables', defaultUnit: 'kg', names: { en: 'Yellow Lemons (Elumichai)', ta: 'எலுமிச்சம்பழம்', ml: 'നാരങ്ങ', hi: 'नींबू', te: 'నిమ్మకాయలు' } },
  { id: 'item-p-35', category: 'perishables', defaultUnit: 'bundles', names: { en: 'Fresh Banana Leaves (Thalhai — Cut)', ta: 'தலை வாழை இலை (கட்டு)', ml: 'വാഴയില കെട്ട്', hi: 'केले के पत्ते (बंडल)', te: 'అరటి ఆకులు (కట్ట)' } },

  // 6. DAIRY & PROVISIONS (பால் பொருட்கள்) — ~15 items
  { id: 'item-d-01', category: 'dairy', defaultUnit: 'L', names: { en: 'Full Cream Milk (Orange Packet / Can)', ta: 'முழு ஆடை பால்', ml: 'പാൽ (ഫുൾ ക്രീം)', hi: 'फुल क्रीम दूध', te: 'పూర్తి మీగడ పాలు' } },
  { id: 'item-d-02', category: 'dairy', defaultUnit: 'L', names: { en: 'Toned Milk (Blue Packet)', ta: 'சாதாரண பால்', ml: 'ടോൺഡ് പാൽ', hi: 'टोन्ड दूध', te: 'టోన్డ్ పాలు' } },
  { id: 'item-d-03', category: 'dairy', defaultUnit: 'kg', names: { en: 'Thick Curd / Yogurt (Thayir)', ta: 'கெட்டித் தயிர்', ml: 'തൈര്', hi: 'गाढ़ा दही', te: 'గడ్డ పెరుగు' } },
  { id: 'item-d-04', category: 'dairy', defaultUnit: 'kg', names: { en: 'Fresh Paneer Blocks (Cottage Cheese)', ta: 'பன்னீர்', ml: 'പന്നീർ', hi: 'ताजा पनीर', te: 'పన్నీర్' } },
  { id: 'item-d-05', category: 'dairy', defaultUnit: 'kg', names: { en: 'Unsalted Cooking Butter (Vennai)', ta: 'வெண்ணெய் (உப்பற்றது)', ml: 'വെണ്ണ', hi: 'सफेद मक्खन', te: 'వెన్న' } },
  { id: 'item-d-06', category: 'dairy', defaultUnit: 'L', names: { en: 'Fresh Heavy Cream (Malai)', ta: 'பிரெஷ் கிரீம் / பாலாடை', ml: 'ഫ്രഷ് ക്രീം', hi: 'ताजी मलाई / क्रीम', te: 'పాల మీగడ' } },
  { id: 'item-d-07', category: 'dairy', defaultUnit: 'tins', names: { en: 'Sweetened Condensed Milk (Milkmaid tin)', ta: 'கண்டன்ஸ்டு மில்க் (டின்)', ml: 'കണ്ടൻസ്ഡ് മിൽക്ക്', hi: 'कन्डेन्स्ड मिल्क', te: 'కండెన్స్‌డ్ మిల్క్ (డబ్బా)' } },
  { id: 'item-d-08', category: 'dairy', defaultUnit: 'kg', names: { en: 'Khoa / Mawa (Unsweetened Milk Solids)', ta: 'கோவா (இனிப்பற்றது)', ml: 'കോവ', hi: 'खोया / मावा', te: 'కోవా / మావా' } },
  { id: 'item-d-09', category: 'dairy', defaultUnit: 'kg', names: { en: 'Skimmed Milk Powder', ta: 'பால் பவுடர்', ml: 'പാൽപ്പൊടി', hi: 'दूध पाउडर', te: 'పాల పొడి' } },
  { id: 'item-d-10', category: 'dairy', defaultUnit: 'kg', names: { en: 'Chenna (Sweet Paneer Base for Rasgulla)', ta: 'சென்னா (இனிப்பு செய்ய)', ml: 'ചെന്ന', hi: 'छेना', te: 'చెన్నా' } },
  { id: 'item-d-11', category: 'dairy', defaultUnit: 'L', names: { en: 'Rose Water (Food Grade)', ta: 'ரோஸ் வாட்டர்', ml: 'റോസ് വാട്ടർ', hi: 'गुलाब जल', te: 'రోజ్ వాటర్' } },
  { id: 'item-d-12', category: 'dairy', defaultUnit: 'L', names: { en: 'Kewra Water (Food Grade)', ta: 'கேவ்டா வாட்டர்', ml: 'കേവഡ വാട്ടർ', hi: 'केवड़ा जल', te: 'కేవడ వాటర్' } },
  { id: 'item-d-13', category: 'dairy', defaultUnit: 'kg', names: { en: 'Edible Silver Foil (Vark for Sweets)', ta: 'வெள்ளி ஏடு (ஸ்வீட் அலங்காரம்)', ml: 'സിൽവർ ഫോയിൽ', hi: 'चांदी का वर्क', te: 'వెండి రేకు' } },
  { id: 'item-d-14', category: 'dairy', defaultUnit: 'kg', names: { en: 'Saffron Strands (Original Kashmir Kunkumapoo)', ta: 'குங்குமப்பூ', ml: 'കുങ്കുമപ്പൂവ്', hi: 'केसर', te: 'కుంకుమ పువ్వు' } },
  { id: 'item-d-15', category: 'dairy', defaultUnit: 'L', names: { en: 'Vanilla Essence Bottle', ta: 'வெண்ணிலா எசென்ஸ்', ml: 'വാനില എസ്സെൻസ്', hi: 'वनिला एसेंस', te: 'వెన్నిలా ఎసెన్స్' } },

  // 7. NUTS & DRY FRUITS (முந்திரி & உலர் பழங்கள்) — ~15 items
  { id: 'item-n-01', category: 'nuts', defaultUnit: 'kg', names: { en: 'Cashew Nuts Whole (W240 Premium)', ta: 'முழு முந்திரி (W240)', ml: 'അണ്ടിപ്പരിപ്പ്', hi: 'काजू साबुत', te: 'జీడిపప్పు (పూర్తి)' } },
  { id: 'item-n-02', category: 'nuts', defaultUnit: 'kg', names: { en: 'Cashew Nuts Split (Kaju Tukda for Payasam)', ta: 'உடைத்த முந்திரி', ml: 'ഉടച്ച അണ്ടിപ്പരിപ്പ്', hi: 'काजू टुकड़ा', te: 'పగిలిన జీడిపప్పు' } },
  { id: 'item-n-03', category: 'nuts', defaultUnit: 'kg', names: { en: 'Almonds Whole (California Badam)', ta: 'பாதாம் பருப்பு', ml: 'ബദാം', hi: 'बादाम', te: 'బాదం పప్పు' } },
  { id: 'item-n-04', category: 'nuts', defaultUnit: 'kg', names: { en: 'Almond Flakes / Slivers', ta: 'சீவிய பாதாம்', ml: 'ബദാം ഫ്ലേക്സ്', hi: 'बादाम कतरन', te: 'బాదం ముక్కలు' } },
  { id: 'item-n-05', category: 'nuts', defaultUnit: 'kg', names: { en: 'Pistachios Green (Unsalted Shelled)', ta: 'பிஸ்தா பருப்பு (உப்பற்றது)', ml: 'പിസ്ത', hi: 'पिस्ता', te: 'పిస్తా పప్పు' } },
  { id: 'item-n-06', category: 'nuts', defaultUnit: 'kg', names: { en: 'Golden Kishmish Raisins (Kismis)', ta: 'உலர் திராட்சை (மஞ்சள்)', ml: 'ഉണക്കമുന്തിരി', hi: 'किशमिश', te: 'కిస్మిస్ (ఎండు ద్రాక్ష)' } },
  { id: 'item-n-07', category: 'nuts', defaultUnit: 'kg', names: { en: 'Black Raisins Seedless (Karuppu Drakshai)', ta: 'கருப்பு உலர் திராட்சை', ml: 'കറുത്ത ഉണക്കമുന്തിരി', hi: 'काली किशमिश', te: 'నల్ల ఎండు ద్రాక్ష' } },
  { id: 'item-n-08', category: 'nuts', defaultUnit: 'kg', names: { en: 'Melon Seeds (Charaz / Magaj)', ta: 'வெள்ளரி விதை / மகஜ்', ml: 'തണ്ണിമത്തൻ വിത്ത്', hi: 'मगज़ / खरबूजे के बीज', te: 'పుచ్చకాయ గింజలు' } },
  { id: 'item-n-09', category: 'nuts', defaultUnit: 'kg', names: { en: 'Chironji / Charoli Seeds (Sara Paruppu)', ta: 'சாரப் பருப்பு', ml: 'ചാരപ്പരിപ്പ്', hi: 'चिरौंजी', te: 'చార పప్పు' } },
  { id: 'item-n-10', category: 'nuts', defaultUnit: 'kg', names: { en: 'Dry Dates (Karjuram / Perichambazham)', ta: 'பேரீச்சம்பழம் / சுக்கான்', ml: 'ഈന്തപ്പഴം', hi: 'छुहारा / खजूर', te: 'ఎండు ఖర్జూరం' } },
  { id: 'item-n-11', category: 'nuts', defaultUnit: 'kg', names: { en: 'Dry Figs (Anjeer / Athipazham)', ta: 'அத்திப்பழம்', ml: 'അത്തിപ്പഴം', hi: 'अंजीर', te: 'అంజీర్' } },
  { id: 'item-n-12', category: 'nuts', defaultUnit: 'kg', names: { en: 'Walnut Halves (Akroot)', ta: 'அக்ரூட் பருப்பு', ml: 'വാൽനട്ട്', hi: 'अखरोट', te: 'వాల్‌నట్' } },
  { id: 'item-n-13', category: 'nuts', defaultUnit: 'kg', names: { en: 'Lotus Seeds (Makhana / Fox Nut)', ta: 'தாமரை விதை / மಖானா', ml: 'താമര വിത്ത്', hi: 'मखाना', te: 'తామర గింజలు / మఖానా' } },
  { id: 'item-n-14', category: 'nuts', defaultUnit: 'kg', names: { en: 'Roasted Groundnuts Whole (Verkadalai)', ta: 'வறுத்த வேர்க்கடலை', ml: 'വറുത്ത നിലക്കടല', hi: 'भुनी मूंगफली', te: 'వేయించిన వేరుశనగ' } },
  { id: 'item-n-15', category: 'nuts', defaultUnit: 'kg', names: { en: 'Tutti Frutti (Red & Green Candied Papaya)', ta: 'டூட்டி ஃப்ரூட்டி', ml: 'ടുട്ടി ഫ്രൂട്ടി', hi: 'टूटी फ्रूटी', te: 'టూటీ ఫ్రూటీ' } },

  // 8. CATERING EQUIPMENT & UTENSILS (பாத்திரங்கள் & சாதனங்கள்) — ~40 items
  { id: 'item-u-01', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Commercial Gas Cylinder — 19kg Red/Blue', ta: 'வணிக கேஸ் சிலிண்டர் (19kg)', ml: 'ഗ്യാസ് സിലിണ്ടർ — 19kg', hi: 'कॉमर्शियल गैस सिलेंडर (19kg)', te: 'వాణిజ్య గ్యాస్ సిలిండర్ — 19kg' } },
  { id: 'item-u-02', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Purified Water Can — 20 Liter Bubble Top', ta: '20 லிட்டர் குடிநீர் கேன்', ml: '20L കുടിവെള്ള കാൻ', hi: '20L पानी का जार', te: '20L మంచినీటి క్యాన్' } },
  { id: 'item-u-03', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Heavy Duty Gas Stove / Burner (T-4 Commercial)', ta: 'வணிக கேஸ் அடுப்பு (பெரியது)', ml: 'വലിയ ഗ്യാസ് അടുപ്പ്', hi: 'बड़ा कमर्शियल भट्टी चूल्हा', te: 'పెద్ద గ్యాస్ పొయ్యి' } },
  { id: 'item-u-04', category: 'utensils', defaultUnit: 'pcs', names: { en: 'High Pressure Gas Regulator & Pipe Set', ta: 'ஹை-பிரஷர் கேஸ் ரெகுலேட்டர் & பைப்', ml: 'ഗ്യാസ് റെഗുലേറ്റർ സെറ്റ്', hi: 'गैस रेगुलेटर और पाइप सेट', te: 'గ్యాస్ రెగ్యులేటర్ & పైపు సెట్' } },
  { id: 'item-u-05', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Sambar / Rasam Drum — 50 Liter', ta: '50L எவர்சில்வர் சாம்பார் அண்டா', ml: '50L സാമ്പാർ പാത്രം', hi: '50L सांभर बड़ा पतीला', te: '50L సాంబార్ గిన్నె' } },
  { id: 'item-u-06', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Rice Boiler Vessel — 100 Liter', ta: '100L எவர்சில்வர் சாதம் வடிக்க அண்டா', ml: '100L ചോറ് വെക്കുന്ന പാത്രം', hi: '100L चावल उबालने का भगोना', te: '100L అన్నం వండే పెద్ద గిన్నె' } },
  { id: 'item-u-07', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Commercial Idli Steamer Box (54 Idlis capacity)', ta: 'இட்லி குக்கர் பெட்டி (54 இட்லி)', ml: 'ഇഡ്ഡലി ചെമ്പ് (54 ഇഡ്ഡലി)', hi: 'इड़ली स्टीमर बॉक्स (54 इड़ली)', te: 'ఇడ్లీ స్టీమర్ బాక్స్ (54 ఇడ్లీలు)' } },
  { id: 'item-u-08', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Heavy Iron Kadai / Wok — 36 Inch Deep Frying', ta: '36 இன்ச் இரும்பு கடாய் (பொரிப்பதற்கு)', ml: '36 ഇഞ്ച് ഇരുമ്പ് ചീനച്ചട്ടി', hi: '36 इंच लोहे की कढ़ाई', te: '36 అంగుళాల ఇనప కడాయి' } },
  { id: 'item-u-09', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Heavy Dosa Tawa / Griddle — 4 Foot Rectangular', ta: '4 அடி தோசை கல் (இரும்பு)', ml: '4 അടി ദോശ കല്ല്', hi: '4 फीट लोहे का तवा', te: '4 అడుగుల ఇనప పెనం' } },
  { id: 'item-u-10', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Buffing Chafing Dish with Burner', ta: 'பஃபே சேஃபிங் டிஷ் (சூடாக வைக்க)', ml: 'ബഫെ ഡിഷ്', hi: 'बुफे चैफिंग डिश वार्मर', te: 'బుఫే వార్మర్ డిష్' } },
  { id: 'item-u-11', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Serving Bucket with Spoon (For Sambar/Curry)', ta: 'பரிமாறும் எவர்சில்வர் வாளி & கரண்டி', ml: 'വിളമ്പുന്ന ബക്കറ്റും തവിയും', hi: 'परोसने की बाल्टी और चम्मच', te: 'వడ్డించే బకెట్ & గరిటె' } },
  { id: 'item-u-12', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Long Handle Stainless Steel Ladle (Jallikarandi / Slotted)', ta: 'ஜல்லிக்கரண்டி (நீள கைப்பிடி)', ml: 'വലിയ സുഷിര തവി', hi: 'बड़ा झारा / पौनी', te: 'పెద్ద చిల్లుల గరిటె' } },
  { id: 'item-u-13', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Long Handle Heavy Stirring Spoon (Thuduppu)', ta: 'துடுப்பு கரண்டி (கிண்டுவதற்கு)', ml: 'വലിയ ഇളക്കുന്ന തവി', hi: 'बड़ा करछुल / पलटा', te: 'పెద్ద కలపడపు గరిటె' } },
  { id: 'item-u-14', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Water Serving Jug — 2 Liter', ta: '2 லிட்டர் தண்ணீர் ஜக்', ml: '2L വാട്ടർ ജഗ്ഗ്', hi: '2L पानी जग', te: '2L నీటి జగ్గు' } },
  { id: 'item-u-15', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Dining Tumbler / Glass (200ml)', ta: 'எவர்சில்வர் டம்ளர் (200ml)', ml: 'സ്റ്റീൽ ഗ്ലാസ് (200ml)', hi: 'स्टील का गिलास (200ml)', te: 'స్టీల్ గ్లాసు (200ml)' } },
  { id: 'item-u-16', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Round Thali Dining Plate (12 Inch)', ta: '12 இன்ச் எவர்சில்வர் தட்டு', ml: '12 ഇഞ്ച് സ്റ്റീൽ പ്ലേറ്റ്', hi: '12 इंच स्टील की थाली', te: '12 అంగుళాల స్టీల్ కంచం' } },
  { id: 'item-u-17', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Melamine Buffet Plate (Square / Round Heavy)', ta: 'மெலமைன் பஃபே தட்டு', ml: 'മെലാമിൻ ബഫെ പ്ലേറ്റ്', hi: 'मेलामाइन बुफे प्लेट', te: 'మెలామిన్ బుఫే ప్లేట్' } },
  { id: 'item-u-18', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Stainless Steel Spoons (Dining size)', ta: 'எவர்சில்வர் ஸ்பூன்', ml: 'സ്റ്റീൽ സ്പൂൺ', hi: 'स्टील का चम्मच', te: 'స్టీల్ చెంచా' } },
  { id: 'item-u-19', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Plastic Storage Crate — Large Stackable (For Vegetables)', ta: 'காய்கறி வைக்கும் பிளாஸ்டிக் கிரேட்', ml: 'പച്ചക്കറി പ്ലാസ്റ്റിക് പെട്ടി', hi: 'सब्जी की प्लास्टिक क्रेट', te: 'కూరగాయల ప్లాస్టిక్ క్రేట్' } },
  { id: 'item-u-20', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Insulated Hot Box / Thermos Food Carrier — 20 Liter', ta: '20L ஹாட் பாக்ஸ் (சூடு தாங்கும்)', ml: '20L ഹോട്ട് ബോക്സ്', hi: '20L इंसुलेटेड हॉट बॉक्स', te: '20L వేడిని ఆపే హాట్ బాక్స్' } },
  { id: 'item-u-21', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Commercial Wet Grinder — 10 Liter Tilting (For Idli Batter)', ta: '10L சாய்வு கிரைண்டர் (மாவு அரைக்க)', ml: '10L വെറ്റ് ഗ്രൈൻഡർ', hi: '10L कमर्शियल वेट ग्राइंडर', te: '10L కమర్షియల్ వెట్ గ్రైండర్' } },
  { id: 'item-u-22', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Commercial Coconut Scraper Machine (Electric)', ta: 'மின்சார தேங்காய் துருவி இயந்திரம்', ml: 'തേങ്ങ ചിരകൽ മെഷീൻ', hi: 'नारियल कसने की मशीन', te: 'కొబ్బరి తురుము యంత్రం' } },
  { id: 'item-u-23', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Commercial Potato / Vegetable Peeler Machine', ta: 'காய்கறி தோல் உரிக்கும் இயந்திரம்', ml: 'പച്ചക്കറി തൊലി കളയുന്ന മെഷീൻ', hi: 'सब्जी छीलने की मशीन', te: 'కూరగాయల తొక్క తీసే యంత్రం' } },
  { id: 'item-u-24', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Heavy Duty Chef Knife — Stainless Steel 10 Inch', ta: '10 இன்ச் செஃப் கத்தி', ml: '10 ഇഞ്ച് ഷെഫ് കത്തി', hi: '10 इंच शेफ चाकू', te: '10 అంగుళాల షెఫ్ కత్తి' } },
  { id: 'item-u-25', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Traditional Aruval / Boti (Floor Chopping Blade)', ta: 'அரிவாள்மனை / போட்டி', ml: 'അരിവാൾമണ', hi: 'पारंपरिक सब्जी काटने का दरांती', te: 'కత్తిపీట' } },
  { id: 'item-u-26', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Large Wooden Chopping Board / Block', ta: 'மர காய்கறி வெட்டும் பலகை', ml: 'മരത്തിന്റെ കട്ടിംഗ് ബോർഡ്', hi: 'लकड़ी का कटिंग बोर्ड', te: 'చెక్క కూరగాయల కోత బల్ల' } },
  { id: 'item-u-27', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Aluminium Colander / Strainer Bowl — 24 Inch', ta: '24 இன்ச் அலுமினிய வடிகட்டி கூடை', ml: '24 ഇഞ്ച് അരിച്ചെടുക്കുന്ന പാത്രം', hi: '24 इंच एल्यूमीनियम छलनी बर्तन', te: '24 అంగుళాల వడకట్టే గిన్నె' } },
  { id: 'item-u-28', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Industrial Exhaust Fan / Chimney Filter Unit', ta: 'புகை வெளியேற்றும் மின்விசிறி', ml: 'എക്സോസ്റ്റ് ഫാൻ', hi: 'एग्जॉस्ट पंखा / चिमनी', te: 'పొగ గొట్టపు పంకా' } },
  { id: 'item-u-29', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Digital Weighing Scale — 100kg Capacity Tabletop', ta: '100 கிலோ டிஜிட்டல் எடை இயந்திரம்', ml: '100kg ഡിജിറ്റൽ ത്രാസ്', hi: '100kg डिजिटल कांटा मशीन', te: '100kg డిజిటల్ త్రాసు' } },
  { id: 'item-u-30', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Digital Kitchen Scale — 5kg Precision (For Spices)', ta: '5 கிலோ மசாலா எடை இயந்திரம்', ml: '5kg ചെറിയ ഡിജിറ്റൽ ത്രാസ്', hi: '5kg छोटी कांटा मशीन', te: '5kg చిన్న డిజిటల్ త్రాసు' } },
  { id: 'item-u-31', category: 'utensils', defaultUnit: 'bundles', names: { en: 'Areca Palm Leaf Plates — Eco-friendly 12 Inch (Bundle of 100)', ta: 'பாக்குமட்டை தட்டு 12 இன்ச் (100 கட்டு)', ml: 'പാള പാത്രം 12 ഇഞ്ച് (100 കെട്ട്)', hi: 'सुपारी के पत्ते की प्लेट (100 पीस)', te: 'అడవి పోక ఆకు కంచాలు (100 కట్ట)' } },
  { id: 'item-u-32', category: 'utensils', defaultUnit: 'bundles', names: { en: 'Paper Buffet Roll / Table Cover Roll — 50 Meter White', ta: 'பஃபே டேபிள் பேப்பர் ரோல் (50 மீட்டர்)', ml: 'ടേബിൾ പേപ്പർ റോൾ (50m)', hi: 'टेबल पेपर रोल (50 मीटर)', te: 'బల్ల కాగితపు రోల్ (50 మీటర్లు)' } },
  { id: 'item-u-33', category: 'utensils', defaultUnit: 'bundles', names: { en: 'Disposable Paper Cups — 150ml Coffee/Tea (Box of 1000)', ta: '150ml பேப்பர் கப் (1000 பெட்டி)', ml: 'പേപ്പർ കപ്പ് (1000 ബോക്സ്)', hi: 'कागज के कप (1000 का डिब्बा)', te: 'కాగితపు కప్పులు (1000 పెట్టె)' } },
  { id: 'item-u-34', category: 'utensils', defaultUnit: 'bundles', names: { en: 'Disposable Water Cups — 200ml Transparent (Box of 2000)', ta: '200ml தண்ணீர் பிளாஸ்டிக் கப் (2000)', ml: 'വെള്ളം കുടിക്കുന്ന കപ്പ് (2000)', hi: 'पानी के गिलास (2000 का डिब्बा)', te: 'నీటి ప్లాస్టిక్ కప్పులు (2000)' } },
  { id: 'item-u-35', category: 'utensils', defaultUnit: 'bundles', names: { en: 'Paper Napkins / Tissue Rolls — Soft Ply (Bundle of 50 packs)', ta: 'டிஸ்யூ பேப்பர் நாப்கின் (50 பாக்கெட்)', ml: 'ടിഷ്യൂ പേപ്പർ (50 പാക്കറ്റ്)', hi: 'टिश्यू पेपर नैपकिन (50 पैकेट)', te: 'టిష్యూ పేపర్ (50 ప్యాకెట్లు)' } },
  { id: 'item-u-36', category: 'utensils', defaultUnit: 'bundles', names: { en: 'Garbage Bags — Jumbo Heavy Duty Black (Pack of 50)', ta: 'பெரிய குப்பை பை (50 எண்ணிக்கை)', ml: 'വലിയ മാലിന്യ കവർ (50)', hi: 'बड़ी कूड़े की थैली (50 पीस)', te: 'పెద్ద చెత్త సంచులు (50)' } },
  { id: 'item-u-37', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Commercial Floor Mop & Wringer Bucket Trolley', ta: 'தரை துடைக்கும் மாப் & வாளி ட்ராலி', ml: 'തര തുടയ്ക്കുന്ന മോപ്പ് സെറ്റ്', hi: 'फर्श पोछा और बाल्टी ट्रॉली', te: 'నేల తుడిచే మాప్ & బకెట్' } },
  { id: 'item-u-38', category: 'utensils', defaultUnit: 'L', names: { en: 'Food Grade Dishwashing Liquid Can — 5 Liter (Vim/Pril)', ta: '5L பாத்திரம் கழுவும் திரவம்', ml: '5L പാത്രം കഴുകുന്ന ലിക്വിഡ്', hi: '5L बर्तन धोने का लिक्विड', te: '5L గిన్నెలు కడిగే ద్రవం' } },
  { id: 'item-u-39', category: 'utensils', defaultUnit: 'pcs', names: { en: 'Heavy Duty Scrubbing Pads & Stainless Steel Scourers (Pack of 24)', ta: 'பாத்திரம் தேய்க்கும் ஸ்டீல் நார் (24)', ml: 'സ്റ്റീൽ സ്ക്രബ്ബർ (24 പാക്കറ്റ്)', hi: 'स्टील जूना / स्क्रबर (24 पीस)', te: 'స్టీల్ స్క్రబ్బర్ (24 ప్యాకెట్)' } },
  { id: 'item-u-40', category: 'utensils', defaultUnit: 'pcs', names: { en: 'First Aid Medical Kit Box (Commercial Kitchen Emergency)', ta: 'முதலுதவி பெட்டி (சமையலறை அவசரம்)', ml: 'ഫസ്റ്റ് എയ്ഡ് ബോക്സ്', hi: 'किचन प्राथमिक चिकित्सा किट', te: 'ప్రథమ చికిత్స పెట్టె' } }
];

// Ensure module support for browser and node tests
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SOUTH_INDIAN_CATALOG };
} else {
  window.SOUTH_INDIAN_CATALOG = SOUTH_INDIAN_CATALOG;
}
